" Name:         Cobange
" Description:  Cobange
" Author:       Alvaro Muñoz <alvaro@pwntester.com>
" Maintainer:   Alvaro Muñoz <alvaro@pwntester.com>
" License:      Vim License (see `:help license`)
" Last Updated: Sun Dec 29 00:17:16 2019

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'cobange'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#020511', '#902020', '#3AD900', '#FFC600',
        \ '#0050A4', '#967EFB', '#80FCFF', '#CCCCCC', '#626262', '#FF0000',
        \ '#88FF88', '#F2ED7F', '#0088FF', '#FF628C', '#668799', '#FFFFFF']
  if has('nvim')
    let g:terminal_color_0 = '#020511'
    let g:terminal_color_1 = '#902020'
    let g:terminal_color_2 = '#3AD900'
    let g:terminal_color_3 = '#FFC600'
    let g:terminal_color_4 = '#0050A4'
    let g:terminal_color_5 = '#967EFB'
    let g:terminal_color_6 = '#80FCFF'
    let g:terminal_color_7 = '#CCCCCC'
    let g:terminal_color_8 = '#626262'
    let g:terminal_color_9 = '#FF0000'
    let g:terminal_color_10 = '#88FF88'
    let g:terminal_color_11 = '#F2ED7F'
    let g:terminal_color_12 = '#0088FF'
    let g:terminal_color_13 = '#FF628C'
    let g:terminal_color_14 = '#668799'
    let g:terminal_color_15 = '#FFFFFF'
  endif
  hi! link Character Constant
  hi! link QuickFixLine Search
  hi! link Boolean Constant
  hi! link Conditional Statement
  hi! link Define PreProc
  hi! link Debug Special
  hi! link Exception Statement
  hi! link Float Number
  hi! link Include PreProc
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Macro PreProc
  hi! link Number Constant
  hi! link PreCondit PreProc
  hi! link Repeat Statement
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link Tag Special
  hi! link Typedef Type
  hi! link StatusLine Normal
  hi! link StatusLineNC NormalNC
  hi Directory guifg=#668799 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=NONE guibg=#902020 guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#17252c guibg=#020511 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#9E9E9E guibg=#444444 guisp=NONE gui=italic cterm=italic
  hi MatchParen guifg=#FFFFFF guibg=#0050A4 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MoreMsg guifg=#88FF88 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#FFFFFF guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#17252c guibg=#020511 guisp=NONE gui=NONE cterm=NONE
  hi EndOfBufferNC guifg=#3A3A3A guibg=#17252c guisp=NONE gui=NONE cterm=NONE
  hi PMenu guifg=#CCCCCC guibg=#3A3A3A guisp=NONE gui=NONE cterm=NONE
  hi PMenuSel guifg=#3A3A3A guibg=#FFC600 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#CCCCCC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#3AD900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#FFFFFF guibg=#0088FF guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#FFFFFF guibg=#0088FF guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#444444 guibg=#1C1C1C guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=NONE guibg=NONE guisp=#FF0000 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=#00AAFF gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=#80FCFF gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=#967EFB gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi TabLine guifg=#CCCCCC guibg=#1C1C1C guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#CCCCCC guibg=#1C1C1C guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#0050A4 guibg=#00AAFF guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#3AD900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#FF0000 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#EB939A guibg=#3A3A3A guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#0088FF guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#FF628C guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#3AD900 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#FF9A00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#FF9A00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#0088FF guibg=NONE guisp=NONE gui=italic cterm=italic
  hi PreProc guifg=#FF9A00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#FF9A00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#0088FF guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Special guifg=#88FF88 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#668799 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#668799 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi Ignore guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=NONE guibg=#902020 guisp=NONE gui=italic cterm=italic
  hi Todo guifg=NONE guibg=#0088FF guisp=NONE gui=italic cterm=italic
  hi ColorColumn guifg=NONE guibg=#020511 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guisp=NONE gui=NONE cterm=NONE
  hi Normal guifg=#FFFFFF guibg=#020511 guisp=NONE gui=NONE cterm=NONE
  hi NormalNC guifg=#FFFFFF guibg=#17252c guisp=NONE gui=NONE cterm=NONE
  hi NormalFloat guifg=#FFFFFF guibg=#17252c guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=#3A3A3A guisp=NONE gui=NONE cterm=NONE
  hi CursorIM guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#3A3A3A guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#17252c guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#626262 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#FFFFFF guibg=#0050A4 guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi DiffAdd guifg=#1C1C1C guibg=#3AD900 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=#1C1C1C guibg=#0088FF guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#1C1C1C guibg=#0088FF guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#FFFFFF guibg=#FF0000 guisp=NONE gui=NONE cterm=NONE
  hi xmlTag guifg=#CCCCCC guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi xmlTagName guifg=#80FCFF guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi xmlEndTag guifg=#80FCFF guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi xmlAttrib guifg=#FF9A00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi xmlString guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi xmlEqual guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi xmlDocTypeDecl guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi xmlInlineDTD guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link xmlTodo Todo
  hi! link xmlNamespace Tag
  hi! link xmlEntity Statement
  hi! link xmlEntityPunct Type
  hi! link xmlAttribPunct Comment
  hi! link xmlComment Comment
  hi! link xmlCommentStart Comment
  hi! link xmlCommentPart Comment
  hi! link xmlCommentError Error
  hi! link xmlError Error
  hi! link xmlProcessingDelim Comment
  hi! link xmlProcessing Type
  hi! link xmlCdata String
  hi! link xmlCdataCdata Statement
  hi! link xmlCdataStart Type
  hi! link xmlCdataEnd Type
  hi! link xmlDocTypeKeyword Statement
  hi Defx_filename_root guifg=#668799 guisp=NONE gui=NONE cterm=NONE
  hi deniteMatched guifg=#00AAFF guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi deniteMatchedChar guifg=#00AAFF guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi DiffAdded guifg=#1C1C1C guibg=#3AD900 guisp=NONE gui=NONE cterm=NONE
  hi DiffRemoved guifg=#FFFFFF guibg=#FF0000 guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeHelp guifg=#0050A4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeUp guifg=#0050A4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeOpenable guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeClosable guifg=#FF0000 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeDir guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeDirSlash guifg=#1C1C1C guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NERDTreeExecFile guifg=#967EFB guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link DirvishPathTail Comment
  hi! link DirvishPathHead Function
  hi! link DirvishSuffix Identifier
  hi! link goDiagnosticError SpellBad
  hi! link goDiagnosticWarning SpellRare
  hi LspDiagnosticsError guifg=#FF0000 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LspDiagnosticsWarning guifg=#FFC600 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LspDiagnosticInformation guifg=#00AAFF guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LspDiagnosticHint guifg=#00AAFF guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi LspDiagnosticsUnderline guifg=NONE guibg=NONE guisp=#FFFFFF gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi LspDiagnosticsUnderlineError guifg=NONE guibg=NONE guisp=#FF0000 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi LspDiagnosticsUnderlineWarning guifg=NONE guibg=NONE guisp=#FFC600 gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi LspDiagnosticsUnderlineInfo guifg=NONE guibg=NONE guisp=#00AAFF gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi LspDiagnosticsUnderlineHint guifg=NONE guibg=NONE guisp=#00AAFF gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi LspReferenceText guifg=NONE guibg=#444444 guisp=NONE gui=bold,italic cterm=bold,italic
  hi LspReferenceRead guifg=NONE guibg=#444444 guisp=NONE gui=bold,italic cterm=bold,italic
  hi LspReferenceWrite guifg=NONE guibg=#444444 guisp=NONE gui=bold,italic cterm=bold,italic
  hi! link BufTabLineCurrent TabLineSel
  hi! link BufTabLineActive TabLine
  hi! link BufTabLineHidden TabLine
  hi! link BufTabLineFill TabLineFill
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
    hi Operator gui=NONE cterm=NONE
    hi Structure gui=NONE cterm=NONE
    hi Error gui=NONE cterm=NONE
    hi Todo gui=NONE cterm=NONE
    hi LspReferenceText gui=bold cterm=bold
    hi LspReferenceRead gui=bold cterm=bold
    hi LspReferenceWrite gui=bold cterm=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi! link Character Constant
  hi! link QuickFixLine Search
  hi! link Boolean Constant
  hi! link Conditional Statement
  hi! link Define PreProc
  hi! link Debug Special
  hi! link Exception Statement
  hi! link Float Number
  hi! link Include PreProc
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Macro PreProc
  hi! link Number Constant
  hi! link PreCondit PreProc
  hi! link Repeat Statement
  hi! link SpecialChar Special
  hi! link SpecialComment Special
  hi! link Tag Special
  hi! link Typedef Type
  hi! link StatusLine Normal
  hi! link StatusLineNC NormalNC
  hi Directory ctermfg=67 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=NONE ctermbg=88 cterm=NONE
  hi VertSplit ctermfg=235 ctermbg=232 cterm=NONE
  hi Folded ctermfg=247 ctermbg=238 cterm=italic
  hi MatchParen ctermfg=231 ctermbg=25 cterm=NONE
  hi ModeMsg ctermfg=NONE ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=120 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=231 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=235 ctermbg=232 cterm=NONE
  hi EndOfBufferNC ctermfg=237 ctermbg=235 cterm=NONE
  hi PMenu ctermfg=252 ctermbg=237 cterm=NONE
  hi PMenuSel ctermfg=237 ctermbg=220 cterm=NONE
  hi PmenuSbar ctermfg=241 ctermbg=NONE cterm=NONE
  hi PmenuThumb ctermfg=252 ctermbg=NONE cterm=NONE
  hi Question ctermfg=40 ctermbg=NONE cterm=NONE
  hi Search ctermfg=231 ctermbg=33 cterm=NONE
  hi IncSearch ctermfg=231 ctermbg=33 cterm=NONE
  hi SpecialKey ctermfg=238 ctermbg=234 cterm=NONE
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi TabLine ctermfg=252 ctermbg=234 cterm=NONE
  hi TabLineFill ctermfg=252 ctermbg=234 cterm=NONE
  hi TabLineSel ctermfg=25 ctermbg=39 cterm=NONE
  hi Title ctermfg=40 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=196 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=174 ctermbg=237 cterm=NONE
  hi Comment ctermfg=33 ctermbg=NONE cterm=italic
  hi Constant ctermfg=204 ctermbg=NONE cterm=NONE
  hi String ctermfg=40 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=208 ctermbg=NONE cterm=NONE
  hi Function ctermfg=220 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=208 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=33 ctermbg=NONE cterm=italic
  hi PreProc ctermfg=208 ctermbg=NONE cterm=NONE
  hi Type ctermfg=220 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=208 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=33 ctermbg=NONE cterm=italic
  hi Special ctermfg=120 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=67 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=67 ctermbg=NONE cterm=underline
  hi Ignore cterm=NONE
  hi Error ctermfg=NONE ctermbg=88 cterm=italic
  hi Todo ctermfg=NONE ctermbg=33 cterm=italic
  hi ColorColumn ctermfg=NONE ctermbg=232 cterm=NONE
  hi Conceal cterm=NONE
  hi Normal ctermfg=231 ctermbg=232 cterm=NONE
  if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
    set background=dark
  endif
  hi NormalNC ctermfg=231 ctermbg=235 cterm=NONE
  hi NormalFloat ctermfg=231 ctermbg=235 cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorIM cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLineNr ctermfg=220 ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=241 ctermbg=NONE cterm=NONE
  hi SignColumn ctermfg=241 ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=241 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=231 ctermbg=25 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=NONE cterm=underline
  hi DiffAdd ctermfg=234 ctermbg=40 cterm=NONE
  hi DiffChange ctermfg=234 ctermbg=33 cterm=NONE
  hi DiffText ctermfg=234 ctermbg=33 cterm=NONE
  hi DiffDelete ctermfg=231 ctermbg=196 cterm=NONE
  hi xmlTag ctermfg=252 ctermbg=NONE cterm=NONE
  hi xmlTagName ctermfg=123 ctermbg=NONE cterm=NONE
  hi xmlEndTag ctermfg=123 ctermbg=NONE cterm=NONE
  hi xmlAttrib ctermfg=208 ctermbg=NONE cterm=NONE
  hi xmlString ctermfg=220 ctermbg=NONE cterm=NONE
  hi xmlEqual ctermfg=220 ctermbg=NONE cterm=NONE
  hi xmlDocTypeDecl ctermfg=220 ctermbg=NONE cterm=NONE
  hi xmlInlineDTD ctermfg=220 ctermbg=NONE cterm=NONE
  hi! link xmlTodo Todo
  hi! link xmlNamespace Tag
  hi! link xmlEntity Statement
  hi! link xmlEntityPunct Type
  hi! link xmlAttribPunct Comment
  hi! link xmlComment Comment
  hi! link xmlCommentStart Comment
  hi! link xmlCommentPart Comment
  hi! link xmlCommentError Error
  hi! link xmlError Error
  hi! link xmlProcessingDelim Comment
  hi! link xmlProcessing Type
  hi! link xmlCdata String
  hi! link xmlCdataCdata Statement
  hi! link xmlCdataStart Type
  hi! link xmlCdataEnd Type
  hi! link xmlDocTypeKeyword Statement
  hi Defx_filename_root ctermfg=67 cterm=NONE
  hi deniteMatched ctermfg=39 ctermbg=NONE cterm=NONE
  hi deniteMatchedChar ctermfg=39 ctermbg=NONE cterm=NONE
  hi DiffAdded ctermfg=234 ctermbg=40 cterm=NONE
  hi DiffRemoved ctermfg=231 ctermbg=196 cterm=NONE
  hi NERDTreeHelp ctermfg=25 ctermbg=NONE cterm=NONE
  hi NERDTreeUp ctermfg=25 ctermbg=NONE cterm=NONE
  hi NERDTreeOpenable ctermfg=220 ctermbg=NONE cterm=NONE
  hi NERDTreeClosable ctermfg=196 ctermbg=NONE cterm=NONE
  hi NERDTreeDir ctermfg=220 ctermbg=NONE cterm=NONE
  hi NERDTreeDirSlash ctermfg=234 ctermbg=NONE cterm=NONE
  hi NERDTreeExecFile ctermfg=105 ctermbg=NONE cterm=NONE
  hi! link DirvishPathTail Comment
  hi! link DirvishPathHead Function
  hi! link DirvishSuffix Identifier
  hi! link goDiagnosticError SpellBad
  hi! link goDiagnosticWarning SpellRare
  hi LspDiagnosticsError ctermfg=196 ctermbg=NONE cterm=NONE
  hi LspDiagnosticsWarning ctermfg=220 ctermbg=NONE cterm=NONE
  hi LspDiagnosticInformation ctermfg=39 ctermbg=NONE cterm=NONE
  hi LspDiagnosticHint ctermfg=39 ctermbg=NONE cterm=NONE
  hi LspDiagnosticsUnderline ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi LspDiagnosticsUnderlineError ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi LspDiagnosticsUnderlineWarning ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi LspDiagnosticsUnderlineInfo ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi LspDiagnosticsUnderlineHint ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi LspReferenceText ctermfg=NONE ctermbg=238 cterm=bold,italic
  hi LspReferenceRead ctermfg=NONE ctermbg=238 cterm=bold,italic
  hi LspReferenceWrite ctermfg=NONE ctermbg=238 cterm=bold,italic
  hi! link BufTabLineCurrent TabLineSel
  hi! link BufTabLineActive TabLine
  hi! link BufTabLineHidden TabLine
  hi! link BufTabLineFill TabLineFill
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
    hi Operator cterm=NONE
    hi Structure cterm=NONE
    hi Error cterm=NONE
    hi Todo cterm=NONE
    hi LspReferenceText cterm=bold
    hi LspReferenceRead cterm=bold
    hi LspReferenceWrite cterm=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background:  dark
" Color: black			      #1C1C1C ~
" Color: darkest_grey			#3A3A3A ~
" Color: darker_grey			#444444 ~
" Color: dark_grey			  #626262 ~
" Color: light_grey			  #9E9E9E ~
" Color: lightest_grey		#CCCCCC ~
" Color: white			      #FFFFFF ~
" Color: dark_orange			#FF9A00 ~
" Color: yellow			      #FFC600 ~
" Color: light_yellow			#F2ED7F ~
" Color: green			      #3AD900 ~
" Color: light_green			#88FF88 ~
" Color: purple			      #967EFB ~
" Color: darker_cobalt		#020511 ~
" Color: cobalt			      #17252c ~
" Color: darker_blue			#0050A4 ~
" Color: dark_blue			  #0088FF ~
" Color: blue			        #00AAFF ~
" Color: light_blue			  #80FCFF ~
" Color: dirty_blue			  #668799 ~
" Color: dark_red			    #902020 ~
" Color: red			        #FF0000 ~
" Color: dark_pink			  #FF628C ~
" Color: dirty_pink			  #EB939A ~
" Term Colors: darker_cobalt dark_red green yellow darker_blue purple light_blue lightest_grey
" Term Colors: dark_grey red light_green light_yellow dark_blue dark_pink dirty_blue white
" vim: et ts=2 sw=2
